package xbeerelay;

/**
 * Thrown if there's a problem with a relay.
 * 
 * @author <a href=mailto:cdw38@cornell.edu>Casey Worthington</a>
 *
 */
public class RelayException extends Exception {

	/**
	 *  This was generated by eclipse.
	 */
	private static final long serialVersionUID = 94470605672350502L;

	/**
	 * Creates a new instance of RelayException.
	 */
	public RelayException() {
		super();
	}
	
	public RelayException(Exception inCause) {
		super(inCause);
	}
	
	public RelayException(String inMessage) {
		super(inMessage);
	}
}
